### ISSUE TITLE
Dependecies on some libraries can be removed

### ISSUE THREAD

**Issue by PavelCibulka** [todvora/eet-client#20]
cxf-bundle-compatible

can be replaced with:
cxf-rt-frontend-jaxws
cxf-rt-transports-http

**Comment by todvora** [comment]
Implemented in commit https://github.com/todvora/eet-client/commit/ba8600efaba3d826af93ec2dccc6afcf7bb77ace

Works fine and makes dependencies zip for non-maven users significantly smaller. Thank you!
