### ISSUE TITLE
Podpora Java 10

### ISSUE THREAD

**Issue by Dacesilian** [todvora/eet-client#39]
Dobrý den,
plánujete prosím kód přizpůsobit pro Javu 10?

Aktuálně knihovna pod Javou 10 nefunguje, je třeba přidat některé moduly (což je lepší udělat přidáním Maven závislostí), pak se ale změnily některé metody (např. wss4j Merlin `verifyTrust` se změnila na `protected` a ta `public` vyžaduje navíc `Collection<Pattern> issuerCertConstraints`).

Děkuji.

**Comment by Dacesilian** [comment]
Verze závislostí je vhodné upravit takto:
> <properties>
> 		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
> 		<maven.compile.source>10</maven.compile.source>
> 		<maven.compile.target>10</maven.compile.target>
> 
> 		<cxf.version>3.2.5</cxf.version>
> 		<junit.version>4.12</junit.version>
> 		<slf4j.version>1.7.24</slf4j.version>
> 		<log4j.version>2.11.1</log4j.version>
> 		<maven-failsafe.version>2.19.1</maven-failsafe.version>
> 		<jacoco.version>0.7.7.201606060606</jacoco.version>
> 		<maven-source-plugin.version>3.0.1</maven-source-plugin.version>
> 		<maven-javadoc-plugin.version>2.10.4</maven-javadoc-plugin.version>
> 		<jaxb.version>2.3.0.1</jaxb.version>
> 	</properties>

V testu `MerlinWithCRLDistributionPointsExtensionTest` je možné volat `crypto.verifyTrust(certsPlayground, enableRevocation, subjectCertConstraints, null);`, protože `matchesName` ve třídě `CryptoBase` vrací při `null` `true`. Původní `protected verifyTrust` je volán tak jako tak, tedy by mělo být vše v pořádku.

Nyní testy projdou, nicméně v konzoli hází chyby - `connect timed out` a nedůvěryhodný certifikát (`CertPathValidatorException: Path does not chain with any of the trust anchors`).

**Comment by todvora** [comment]
Super nápad, díky. Bylo by prosím možné změny dodat jako pull request?

**Comment by Dacesilian** [comment]
Ano, https://github.com/todvora/eet-client/pull/40
