### ISSUE TITLE
Inquiry for cooperation

### ISSUE THREAD

**Issue by kposavcevic** [todvora/eet-client#43]
Hi,

We are working on the implementation of EET for one Czech client and we would need help with connecting to Czech Tax Authorities, so we decided to contact you with the hope that you can help us with your esteemed experience.  

At this time, our development team is working on the solution, but we need someone who can help us to connect with Czech Tax Authorities by providing specific local inputs. This would take approximately 3-4 hours of your time per week, depending on the phase of integration. Of course, you would be paid for your time invested.

Please let us know if you are interested in cooperation so we can agree on terms. 

Thank you and best regards, Kristian

**Comment by TBLDK** [comment]
Hi


I have worked with this and has POS Sale computers that tranfer  information to the Czech TaxAutorities
I am from Denmark ))

Tommy Bach Lauritsen
+45 30250222

Fra: kposavcevic <notifications@github.com>
Sendt: 30. marts 2020 13:18
Til: todvora/eet-client <eet-client@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [todvora/eet-client] Inquiry for cooperation (#43)


Hi,

We are working on the implementation of EET for one Czech client and we would need help with connecting to Czech Tax Authorities, so we decided to contact you with the hope that you can help us with your esteemed experience.

At this time, our development team is working on the solution, but we need someone who can help us to connect with Czech Tax Authorities by providing specific local inputs. This would take approximately 3-4 hours of your time per week, depending on the phase of integration. Of course, you would be paid for your time invested.

Please let us know if you are interested in cooperation so we can agree on terms.

Thank you and best regards, Kristian

**Comment by kposavcevic** [comment]
Hi,

thank you for a quick turnaround. I suppose that you know technical requirements for connecting to Czech Tax Authorities? 

Can you please give me your email, so we can continue our conversation there?

Best,
Kristian

**Comment by TBLDK** [comment]
TBL@VIA-SYSTEM.DK<mailto:TBL@VIA-SYSTEM.DK>

Tommy Bach Lauritsen
+45 30250222

Fra: kposavcevic <notifications@github.com>
Sendt: 30. marts 2020 15:45
Til: todvora/eet-client <eet-client@noreply.github.com>
Cc: Tommy Bach Lauritsen <tbl@via-system.dk>; Comment <comment@noreply.github.com>
Emne: Re: [todvora/eet-client] Inquiry for cooperation (#43)


Hi,

thank you for a quick turnaround. I suppose that you know technical requirements for connecting to Czech Tax Authorities?

Can you please give me your email, so we can continue our conversation there?

Best,
Kristian

**Comment by todvora** [comment]
Hi @kposavcevic and @TBLDK,
Awesome networking, thank you both for responding, I like it very much! 

I hope you can get everything working soon. For me, this library was just a side project out of curiosity, so I am probably not the best person for the job. 

Good luck, Tomas.
