### ISSUE TITLE
Remove BouncyCastle

### ISSUE THREAD

**Issue by PavelCibulka** [todvora/eet-client#46]
Bylo by mozne ted odebrat dependency na BouncyCastle:
https://github.com/todvora/eet-client/issues/27

Bug co tomu branil je davno opraveny:
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8175251

**Comment by Dacesilian** [comment]
Ahoj, přidávám se k této prosbě, jestli je to možné: ) Děkuji.

**Comment by todvora** [comment]
Nejaky dobrovolnik na code review? :pray: @PavelCibulka @Dacesilian , diky!

**Comment by Dacesilian** [comment]
@todvora Koukám na to, zjevnou chybu nevidím, ale moc z toho nevykoukám:)

**Comment by PavelCibulka** [comment]
Ja myslim ze ok. My do tedka pouzivame verzi 3.0.0-beta-7 z, ktere byl BouncyCastle oddelan. Zadny problem s tim za ty ctyri a pul roku nebyl. Tady ty zmeny jsou podobne krome CertExpirationChecker, ten tam jeste v te dobe nebyl.

**Comment by todvora** [comment]
Diky za review, BC je pryc v nejnovejsim 4.0.3 release: https://github.com/todvora/eet-client/releases/tag/4.0.3

Kdyby byl nejaky problem, dejte vedet.
