### ISSUE TITLE
reading keystore.p12 sometimes read not keyEntry as a first alias 

### ISSUE THREAD

**Issue by marek-veber** [todvora/eet-client#6]
the code:

```java
final Enumeration<String> aliases = getAliases(keystore);
```

returns aliases of two types:
```java
keystore.isKeyEntry(a) == true
```
and
```java
keystore.isCertificateEntry(a) == true
```

But using method select first one can be **randomly** unvanted CertificateEntry (not required KeyEntry) ;)

So, sometimes initialisation fails with an error such as "bad key format", while using certificate as a key ;(

**Comment by todvora** [comment]
Merged, thank you for your contribution!
